// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: s2s/server.proto

package s2s

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取服务器名请求.
type GetServerNameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerNameReq) Reset() {
	*x = GetServerNameReq{}
	mi := &file_s2s_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerNameReq) ProtoMessage() {}

func (x *GetServerNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_s2s_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerNameReq.ProtoReflect.Descriptor instead.
func (*GetServerNameReq) Descriptor() ([]byte, []int) {
	return file_s2s_server_proto_rawDescGZIP(), []int{0}
}

// 获取服务器名响应.
type GetServerNameResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    string                 `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"` // 服务器名.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerNameResp) Reset() {
	*x = GetServerNameResp{}
	mi := &file_s2s_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerNameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerNameResp) ProtoMessage() {}

func (x *GetServerNameResp) ProtoReflect() protoreflect.Message {
	mi := &file_s2s_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerNameResp.ProtoReflect.Descriptor instead.
func (*GetServerNameResp) Descriptor() ([]byte, []int) {
	return file_s2s_server_proto_rawDescGZIP(), []int{1}
}

func (x *GetServerNameResp) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

var File_s2s_server_proto protoreflect.FileDescriptor

const file_s2s_server_proto_rawDesc = "" +
	"\n" +
	"\x10s2s/server.proto\x12\x03s2s\"\x12\n" +
	"\x10GetServerNameReq\"3\n" +
	"\x11GetServerNameResp\x12\x1e\n" +
	"\n" +
	"serverName\x18\x01 \x01(\tR\n" +
	"serverNameB/Z-github.com/godyy/ggs/internal/protocol/pb/s2sb\x06proto3"

var (
	file_s2s_server_proto_rawDescOnce sync.Once
	file_s2s_server_proto_rawDescData []byte
)

func file_s2s_server_proto_rawDescGZIP() []byte {
	file_s2s_server_proto_rawDescOnce.Do(func() {
		file_s2s_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_s2s_server_proto_rawDesc), len(file_s2s_server_proto_rawDesc)))
	})
	return file_s2s_server_proto_rawDescData
}

var file_s2s_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_s2s_server_proto_goTypes = []any{
	(*GetServerNameReq)(nil),  // 0: s2s.GetServerNameReq
	(*GetServerNameResp)(nil), // 1: s2s.GetServerNameResp
}
var file_s2s_server_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_s2s_server_proto_init() }
func file_s2s_server_proto_init() {
	if File_s2s_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s2s_server_proto_rawDesc), len(file_s2s_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_s2s_server_proto_goTypes,
		DependencyIndexes: file_s2s_server_proto_depIdxs,
		MessageInfos:      file_s2s_server_proto_msgTypes,
	}.Build()
	File_s2s_server_proto = out.File
	file_s2s_server_proto_goTypes = nil
	file_s2s_server_proto_depIdxs = nil
}
