// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: s2s/persist.proto

package s2s

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Actor 保存结果
type ActorSaveResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorSaveResult) Reset() {
	*x = ActorSaveResult{}
	mi := &file_s2s_persist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorSaveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorSaveResult) ProtoMessage() {}

func (x *ActorSaveResult) ProtoReflect() protoreflect.Message {
	mi := &file_s2s_persist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorSaveResult.ProtoReflect.Descriptor instead.
func (*ActorSaveResult) Descriptor() ([]byte, []int) {
	return file_s2s_persist_proto_rawDescGZIP(), []int{0}
}

func (x *ActorSaveResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_s2s_persist_proto protoreflect.FileDescriptor

const file_s2s_persist_proto_rawDesc = "" +
	"\n" +
	"\x11s2s/persist.proto\x12\x03s2s\"+\n" +
	"\x0fActorSaveResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB1Z/github.com/godyy/ggs/internal/core/proto/pb/s2sb\x06proto3"

var (
	file_s2s_persist_proto_rawDescOnce sync.Once
	file_s2s_persist_proto_rawDescData []byte
)

func file_s2s_persist_proto_rawDescGZIP() []byte {
	file_s2s_persist_proto_rawDescOnce.Do(func() {
		file_s2s_persist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_s2s_persist_proto_rawDesc), len(file_s2s_persist_proto_rawDesc)))
	})
	return file_s2s_persist_proto_rawDescData
}

var file_s2s_persist_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_s2s_persist_proto_goTypes = []any{
	(*ActorSaveResult)(nil), // 0: s2s.ActorSaveResult
}
var file_s2s_persist_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_s2s_persist_proto_init() }
func file_s2s_persist_proto_init() {
	if File_s2s_persist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s2s_persist_proto_rawDesc), len(file_s2s_persist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_s2s_persist_proto_goTypes,
		DependencyIndexes: file_s2s_persist_proto_depIdxs,
		MessageInfos:      file_s2s_persist_proto_msgTypes,
	}.Build()
	File_s2s_persist_proto = out.File
	file_s2s_persist_proto_goTypes = nil
	file_s2s_persist_proto_depIdxs = nil
}
