// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: s2s/pid.proto

package s2s

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PID 协议ID.
// 如果协议消息结构来common, 可在其注释中添加 /from_common 标识.
type PID int32

const (
	PID_PUnknown         PID = 0  // 未知.
	PID_PError           PID = 1  // 错误. /from_common
	PID_PActorSaveResult PID = 99 // Actor 保存结果.
)

// Enum value maps for PID.
var (
	PID_name = map[int32]string{
		0:  "PUnknown",
		1:  "PError",
		99: "PActorSaveResult",
	}
	PID_value = map[string]int32{
		"PUnknown":         0,
		"PError":           1,
		"PActorSaveResult": 99,
	}
)

func (x PID) Enum() *PID {
	p := new(PID)
	*p = x
	return p
}

func (x PID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PID) Descriptor() protoreflect.EnumDescriptor {
	return file_s2s_pid_proto_enumTypes[0].Descriptor()
}

func (PID) Type() protoreflect.EnumType {
	return &file_s2s_pid_proto_enumTypes[0]
}

func (x PID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PID.Descriptor instead.
func (PID) EnumDescriptor() ([]byte, []int) {
	return file_s2s_pid_proto_rawDescGZIP(), []int{0}
}

var File_s2s_pid_proto protoreflect.FileDescriptor

const file_s2s_pid_proto_rawDesc = "" +
	"\n" +
	"\rs2s/pid.proto\x12\x03s2s*5\n" +
	"\x03PID\x12\f\n" +
	"\bPUnknown\x10\x00\x12\n" +
	"\n" +
	"\x06PError\x10\x01\x12\x14\n" +
	"\x10PActorSaveResult\x10cB1Z/github.com/godyy/ggs/internal/core/proto/pb/s2sb\x06proto3"

var (
	file_s2s_pid_proto_rawDescOnce sync.Once
	file_s2s_pid_proto_rawDescData []byte
)

func file_s2s_pid_proto_rawDescGZIP() []byte {
	file_s2s_pid_proto_rawDescOnce.Do(func() {
		file_s2s_pid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_s2s_pid_proto_rawDesc), len(file_s2s_pid_proto_rawDesc)))
	})
	return file_s2s_pid_proto_rawDescData
}

var file_s2s_pid_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_s2s_pid_proto_goTypes = []any{
	(PID)(0), // 0: s2s.PID
}
var file_s2s_pid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_s2s_pid_proto_init() }
func file_s2s_pid_proto_init() {
	if File_s2s_pid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s2s_pid_proto_rawDesc), len(file_s2s_pid_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_s2s_pid_proto_goTypes,
		DependencyIndexes: file_s2s_pid_proto_depIdxs,
		EnumInfos:         file_s2s_pid_proto_enumTypes,
	}.Build()
	File_s2s_pid_proto = out.File
	file_s2s_pid_proto_goTypes = nil
	file_s2s_pid_proto_depIdxs = nil
}
