syntax = "proto3";

package common;

option go_package = "github.com/godyy/ggs/internal/infra/actor/protocol/pb/common";

// 错误码
enum ErrCode {
  ECSuccess = 0;       // 成功.
  ECInternalError = 1; // 内部错误.
  ECInvalidPacket = 2; // 无效的数据包.
  ECInvalidToken = 3;  // 无效的令牌.
  ECLoginTimeout = 4;  // 登陆超时.

  // 道具系统 [1000, 1999]
  ECItemNotEnough = 1000; // 道具数量不足.

  // 聊天系统 [2000, 2999]
  ECChatRoomNotExists = 2000;             // 聊天室不存在.
  ECChatRoomMemberIsSelf = 2001;          // 成员是自己.
  ECChatRoomMemberEmpty = 2002;           // 成员列表为空.
  ECChatRoomMemberDuplicate = 2003;       // 成员重复.
  ECChatRoomMemberNotInRoom = 2004;       // 成员不在聊天室.
  ECChatRoomCreateFailed = 2005;          // 创建聊天室失败.
  ECChatRoomMemberAlreadyInRoom = 2006;   // 成员已在聊天室.
  ECChatRoomCantLeave = 2007;             // 不能退出聊天室.
  ECChatRoomMemberIsOwner = 2008;         // 成员是群主.
  ECChatRoomInviteTargetEmpty = 2009;     // 邀请目标为空.
  ECChatRoomInviteTargetDuplicate = 2010; // 邀请目标重复.
  ECChatRoomNoPriviledge = 2011;          // 没有权限.
  ECChatRoomTypeCantInvite = 2012;        // 聊天室类型不能邀请.
  ECChatRoomMemberCountExceed = 2013;     // 成员数量超过最大限制.
  ECChatRoomTypeInvalid = 2014;           // 聊天室类型无效.
}