// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: c2s/item.proto

package c2s

import (
	common "github.com/godyy/ggs/internal/protocol/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 使用道具请求.
type UseItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"` // 道具ID.
	Num           int64                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`       // 使用数量.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseItemReq) Reset() {
	*x = UseItemReq{}
	mi := &file_c2s_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemReq) ProtoMessage() {}

func (x *UseItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemReq.ProtoReflect.Descriptor instead.
func (*UseItemReq) Descriptor() ([]byte, []int) {
	return file_c2s_item_proto_rawDescGZIP(), []int{0}
}

func (x *UseItemReq) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *UseItemReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

// 使用道具响应.
type UseItemResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"`   // 道具ID.
	Num           int64                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`         // 使用数量.
	LeftNum       int64                  `protobuf:"varint,3,opt,name=leftNum,proto3" json:"leftNum,omitempty"` // 剩余数量.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseItemResp) Reset() {
	*x = UseItemResp{}
	mi := &file_c2s_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemResp) ProtoMessage() {}

func (x *UseItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemResp.ProtoReflect.Descriptor instead.
func (*UseItemResp) Descriptor() ([]byte, []int) {
	return file_c2s_item_proto_rawDescGZIP(), []int{1}
}

func (x *UseItemResp) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *UseItemResp) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *UseItemResp) GetLeftNum() int64 {
	if x != nil {
		return x.LeftNum
	}
	return 0
}

// 道具变更通知.
type ItemNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*common.Item         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 道具变更列表.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemNotify) Reset() {
	*x = ItemNotify{}
	mi := &file_c2s_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemNotify) ProtoMessage() {}

func (x *ItemNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemNotify.ProtoReflect.Descriptor instead.
func (*ItemNotify) Descriptor() ([]byte, []int) {
	return file_c2s_item_proto_rawDescGZIP(), []int{2}
}

func (x *ItemNotify) GetItems() []*common.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_c2s_item_proto protoreflect.FileDescriptor

const file_c2s_item_proto_rawDesc = "" +
	"\n" +
	"\x0ec2s/item.proto\x12\x03c2s\x1a\x11common/item.proto\"6\n" +
	"\n" +
	"UseItemReq\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\x05R\x06itemId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\"Q\n" +
	"\vUseItemResp\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\x05R\x06itemId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\x12\x18\n" +
	"\aleftNum\x18\x03 \x01(\x03R\aleftNum\"0\n" +
	"\n" +
	"ItemNotify\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.common.ItemR\x05itemsB/Z-github.com/godyy/ggs/internal/protocol/pb/c2sb\x06proto3"

var (
	file_c2s_item_proto_rawDescOnce sync.Once
	file_c2s_item_proto_rawDescData []byte
)

func file_c2s_item_proto_rawDescGZIP() []byte {
	file_c2s_item_proto_rawDescOnce.Do(func() {
		file_c2s_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_c2s_item_proto_rawDesc), len(file_c2s_item_proto_rawDesc)))
	})
	return file_c2s_item_proto_rawDescData
}

var file_c2s_item_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_c2s_item_proto_goTypes = []any{
	(*UseItemReq)(nil),  // 0: c2s.UseItemReq
	(*UseItemResp)(nil), // 1: c2s.UseItemResp
	(*ItemNotify)(nil),  // 2: c2s.ItemNotify
	(*common.Item)(nil), // 3: common.Item
}
var file_c2s_item_proto_depIdxs = []int32{
	3, // 0: c2s.ItemNotify.items:type_name -> common.Item
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_c2s_item_proto_init() }
func file_c2s_item_proto_init() {
	if File_c2s_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_c2s_item_proto_rawDesc), len(file_c2s_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_c2s_item_proto_goTypes,
		DependencyIndexes: file_c2s_item_proto_depIdxs,
		MessageInfos:      file_c2s_item_proto_msgTypes,
	}.Build()
	File_c2s_item_proto = out.File
	file_c2s_item_proto_goTypes = nil
	file_c2s_item_proto_depIdxs = nil
}
