// Code generated by gexcels; DO NOT EDIT.
// This file was automatically generated and may be overwritten.

package gdconf

// ItemCount 道具数量
type ItemCount struct {
	Id    int32 `bson:"id,omitempty"`    // 道具ID
	Count int32 `bson:"count,omitempty"` // 数量
}
