// Code generated by gexcels; DO NOT EDIT.
// This file was automatically generated and may be overwritten.

package gdconf

import (
	"fmt"
	"sync/atomic"
)

// Load 加载所有配置表
func Load(db *MongoDB) error {
	for _, f := range loadFuncs {
		if err := f(db); err != nil {
			return err
		}
	}
	return nil
}

// LoadTable 加载指定配置表
func LoadTable(db *MongoDB, tableName string) error {
	f, ok := loadFuncMap[tableName]
	if !ok {
		return fmt.Errorf("table[%s] load func not registered", tableName)
	}
	return f(db)
}

var (
	apGlobal  atomic.Pointer[global]  // 全局配置表
	apTabItem atomic.Pointer[tabItem] // 道具
)

// Global 全局配置表
func Global() *global {
	return apGlobal.Load()
}

// TabItem 道具
func TabItem() *tabItem {
	return apTabItem.Load()
}

// loadFunc 配置表加载函数
type loadFunc func(*MongoDB) error

// loadFuncs 配置表加载函数列表
var loadFuncs []loadFunc

// loadFuncMap 配置表加载函数映射
var loadFuncMap map[string]loadFunc

// registerLoadFunc 注册配置表加载函数
func registerLoadFunc(tableName string, f loadFunc) {
	if _, ok := loadFuncMap[tableName]; ok {
		panic(fmt.Errorf("table[%s] load func already registered", tableName))
	}
	loadFuncMap[tableName] = f
	loadFuncs = append(loadFuncs, f)
}

// registerAllLoadFuncs 注册所有配置表加载函数
func registerAllLoadFuncs() {
	loadFuncs = make([]loadFunc, 0, 2)
	loadFuncMap = make(map[string]loadFunc, 2)
	registerLoadFunc("Global", func(db *MongoDB) error {
		t := newGlobal()
		if err := t.load(db); err != nil {
			return err
		}
		apGlobal.Store(t)
		return nil
	})
	registerLoadFunc("Item", func(db *MongoDB) error {
		t := newTabItem()
		if err := t.load(db); err != nil {
			return err
		}
		apTabItem.Store(t)
		return nil
	})
}

func init() {
	registerAllLoadFuncs()
}
