// Code generated by gexcels; DO NOT EDIT.
// This file was automatically generated and may be overwritten.

package gdconf

import (
	"context"
	"errors"
	"time"

	pkgerrors "github.com/pkg/errors"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

type MongoDB = mongo.Database

const (
	collGlobal    = "Global"
	loadBatchSize = 1000
	loadTimeout   = 10 * time.Second
)

func createLoadContext() (context.Context, context.CancelFunc) {
	return context.WithTimeout(context.Background(), loadTimeout)
}

func loadNormal[Entry any](db *MongoDB, collName string, allEntries *[]Entry) error {
	var (
		coll = db.Collection(collName)
		skip = int64(0)
	)

	for {
		ctx, cancel := createLoadContext()

		cursor, err := coll.Find(ctx, bson.M{}, options.Find().SetSkip(skip).SetLimit(loadBatchSize))
		if err != nil {
			cancel()
			return pkgerrors.WithMessagef(err, "[%s][%s] load failed at skip:%d limit:%d", db.Name(), collName, skip, loadBatchSize)
		}

		var entries []Entry
		if err := cursor.All(ctx, &entries); err != nil {
			cancel()
			return pkgerrors.WithMessagef(err, "[%s][%s] decode failed at skip:%d limit:%d", db.Name(), collName, skip, loadBatchSize)
		}

		if errors.Is(err, mongo.ErrNoDocuments) {
			cancel()
			break
		}

		*allEntries = append(*allEntries, entries...)
		skip += int64(len(entries))
		cancel()

		if len(entries) < loadBatchSize {
			break
		}
	}

	return nil
}

func loadGlobal(db *MongoDB, tableName string, t any) error {
	coll := db.Collection(collGlobal)

	ctx, cancel := createLoadContext()
	defer cancel()

	if err := coll.FindOne(ctx, bson.M{"_id": tableName}).Decode(t); err != nil {
		return pkgerrors.WithMessagef(err, "[%s][%s] load failed", db.Name(), tableName)
	}

	return nil
}
