// Code generated by gexcels; DO NOT EDIT.
// This file was automatically generated and may be overwritten.

package gdconf

var itemTypeStrings = map[ItemType]string{
	ItemTypeCurrency: "Currency",
	ItemTypeBox:      "Box",
}

func (e ItemType) String() string {
	return itemTypeStrings[e]
}

var itemSubTypeStrings = map[ItemSubType]string{
	ItemSubTypeNone:    "None",
	ItemSubTypeDiamond: "Diamond",
	ItemSubTypeGold:    "Gold",
}

func (e ItemSubType) String() string {
	return itemSubTypeStrings[e]
}
