// Code generated by gexcels; DO NOT EDIT.
// This file was automatically generated and may be overwritten.

package gdconf

// ItemType 道具类型
type ItemType int32

const (
	ItemTypeCurrency = ItemType(1) // 货币
	ItemTypeBox      = ItemType(2) // 箱子
)

// ItemSubType 道具子类型
type ItemSubType int32

const (
	ItemSubTypeNone    = ItemSubType(0) // 无
	ItemSubTypeDiamond = ItemSubType(1) // 钻石
	ItemSubTypeGold    = ItemSubType(2) // 金币
)

// ChatRoomType 聊天室类型
type ChatRoomType int32

const (
	ChatRoomTypeServer = ChatRoomType(1) // 服务器聊天室
	ChatRoomTypeGroup  = ChatRoomType(2) // 群组聊天室
)
