// Code generated by gexcels; DO NOT EDIT.
// This file was automatically generated and may be overwritten.

package gdconf

// global 全局配置表
type global struct {
	First  int32 `bson:"first,omitempty"`  // 测试1
	Second int64 `bson:"second,omitempty"` // 测试2
}

// load 加载数据
func (t *global) load(db *MongoDB) error {
	return loadGlobal(db, "Global", t)
}

func newGlobal() *global {
	return &global{}
}
