// Code generated by gexcels; DO NOT EDIT.
// This file was automatically generated and may be overwritten.

package gdconf

type Item struct {
	ID    int32  `bson:"_id,omitempty"`   // ID
	Name  string `bson:"name,omitempty"`  // 名称
	Icon  string `bson:"icon,omitempty"`  // 图标
	Level int32  `bson:"level,omitempty"` // level
}

// tabItem 道具
type tabItem struct {
	entries []*Item         // data entries
	byID    map[int32]*Item // mapping by ID
}

func (t *tabItem) All() []*Item { return t.entries }

// ByID mapping by ID
func (t *tabItem) ByID(ID int32) *Item {
	return t.byID[ID]
}

// load 加载数据
func (t *tabItem) load(db *MongoDB) error {
	if err := loadNormal(db, "Item", &t.entries); err != nil {
		return err
	}
	t.init()
	return nil
}

func (t *tabItem) init() {
	t.byID = make(map[int32]*Item, len(t.entries))
	for _, e := range t.entries {
		t.byID[e.ID] = e
	}
}

func newTabItem() *tabItem {
	return &tabItem{
		byID: map[int32]*Item{},
	}
}
