// Code generated by gexcels; DO NOT EDIT.
// This file was automatically generated and may be overwritten.

package gdconf

const TblNameItem = "Item"

type Item struct {
	ID      int32       `bson:"_id,omitempty"`     // ID
	Name    string      `bson:"name,omitempty"`    // 名称
	Type    ItemType    `bson:"type,omitempty"`    // 类型
	SubType ItemSubType `bson:"subType,omitempty"` // 子类型
	Icon    string      `bson:"icon,omitempty"`    // 图标
	Level   int32       `bson:"level,omitempty"`   // level
}

// tblItem 道具
type tblItem struct {
	entries []*Item         // data entries
	byID    map[int32]*Item // mapping by ID
}

func (t *tblItem) All() []*Item { return t.entries }

// ByID mapping by ID
func (t *tblItem) ByID(ID int32) *Item {
	return t.byID[ID]
}

// load 加载数据
func (t *tblItem) load(db *MongoDB) error {
	if err := loadNormal(db, TblNameItem, &t.entries); err != nil {
		return err
	}
	t.init()
	return nil
}

func (t *tblItem) init() {
	t.byID = make(map[int32]*Item, len(t.entries))
	for _, e := range t.entries {
		t.byID[e.ID] = e
	}
}

func newTblItem() *tblItem {
	return &tblItem{
		byID: map[int32]*Item{},
	}
}
