// Code generated by proto/tools/gen_register; DO NOT EDIT.
// 该文件由工具生成，请勿手动编辑。

package registry

import (
	"github.com/godyy/ggs/internal/protocol/pb/c2s"
	"github.com/godyy/ggs/internal/protocol/pb/common"
)

func init() {
	registerC2S(c2s.PID_PError, &common.Error{})
	registerC2S(c2s.PID_PLoginReq, &c2s.LoginReq{})
	registerC2S(c2s.PID_PLoginResp, &c2s.LoginResp{})
	registerC2S(c2s.PID_PLoginCharacterReq, &c2s.LoginCharacterReq{})
	registerC2S(c2s.PID_PLoginCharacterResp, &c2s.LoginCharacterResp{})
	registerC2S(c2s.PID_PDisconnectPush, &c2s.DisconnectPush{})
	registerC2S(c2s.PID_PHeartbeatReq, &c2s.HeartbeatReq{})
	registerC2S(c2s.PID_PHeartbeatResp, &c2s.HeartbeatResp{})
	registerC2S(c2s.PID_PModifyNameReq, &c2s.ModifyNameReq{})
	registerC2S(c2s.PID_PModifyNameResp, &c2s.ModifyNameResp{})
	registerC2S(c2s.PID_PUseItemReq, &c2s.UseItemReq{})
	registerC2S(c2s.PID_PUseItemResp, &c2s.UseItemResp{})
}
