// Code generated by proto/tools/gen_register; DO NOT EDIT.
// 该文件由工具生成，请勿手动编辑。

package registry

import (
	"github.com/godyy/ggs/internal/protocol/pb/common"
	"github.com/godyy/ggs/internal/protocol/pb/s2s"
)

func init() {
	registerS2S(s2s.PID_PError, &common.Error{})
	registerS2S(s2s.PID_PActorSaveResult, &s2s.ActorSaveResult{})
	registerS2S(s2s.PID_PGetServerNameReq, &s2s.GetServerNameReq{})
	registerS2S(s2s.PID_PGetServerNameResp, &s2s.GetServerNameResp{})
}
