// Code generated by proto/tools/gen_register; DO NOT EDIT.
// 该文件由工具生成，请勿手动编辑。

package s2s

import (
	"github.com/godyy/ggs/internal/infra/actor/protocol/pb/common"
	"github.com/godyy/ggs/internal/infra/actor/protocol/pb/s2s"
)

func init() {
	register((*common.Error)(nil))
	register((*s2s.ActorSaveResultNtf)(nil))
	register((*s2s.GetServerNameReq)(nil))
	register((*s2s.GetServerNameResp)(nil))
}
