// Code generated by proto/tools/gen_register; DO NOT EDIT.
// 该文件由工具生成，请勿手动编辑。

package s2s

import (
	"github.com/godyy/ggs/internal/infra/actor/protocol/pb/common"
	"github.com/godyy/ggs/internal/infra/actor/protocol/pb/s2s"
)

func init() {
	register((*common.Error)(nil))
	register((*common.Success)(nil))
	register((*s2s.ActorSaveResultNtf)(nil))
	register((*s2s.ChatHistoryReq)(nil))
	register((*s2s.ChatHistoryResp)(nil))
	register((*s2s.ChatRoomInviteReq)(nil))
	register((*s2s.CreateGroupChatRoomReq)(nil))
	register((*s2s.GetServerNameReq)(nil))
	register((*s2s.GetServerNameResp)(nil))
	register((*s2s.JoinChatRoomReq)(nil))
	register((*s2s.LeaveChatRoomReq)(nil))
	register((*s2s.NotifyJoinChatRoomReq)(nil))
	register((*s2s.NotifyLeaveChatRoomReq)(nil))
	register((*s2s.ReloadGDConfReq)(nil))
	register((*s2s.ReloadGDConfResp)(nil))
	register((*s2s.SendChatMsgReq)(nil))
}
