// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用错误.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 错误码.
	Args          []*ErrArg              `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`  // 错误参数.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetArgs() []*ErrArg {
	if x != nil {
		return x.Args
	}
	return nil
}

// 错误参数
type ErrArg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ErrArg_S
	//	*ErrArg_I
	//	*ErrArg_F
	Value         isErrArg_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrArg) Reset() {
	*x = ErrArg{}
	mi := &file_common_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrArg) ProtoMessage() {}

func (x *ErrArg) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrArg.ProtoReflect.Descriptor instead.
func (*ErrArg) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *ErrArg) GetValue() isErrArg_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ErrArg) GetS() string {
	if x != nil {
		if x, ok := x.Value.(*ErrArg_S); ok {
			return x.S
		}
	}
	return ""
}

func (x *ErrArg) GetI() int64 {
	if x != nil {
		if x, ok := x.Value.(*ErrArg_I); ok {
			return x.I
		}
	}
	return 0
}

func (x *ErrArg) GetF() float64 {
	if x != nil {
		if x, ok := x.Value.(*ErrArg_F); ok {
			return x.F
		}
	}
	return 0
}

type isErrArg_Value interface {
	isErrArg_Value()
}

type ErrArg_S struct {
	S string `protobuf:"bytes,1,opt,name=s,proto3,oneof"` // 字符串值
}

type ErrArg_I struct {
	I int64 `protobuf:"varint,2,opt,name=i,proto3,oneof"` // 整形值
}

type ErrArg_F struct {
	F float64 `protobuf:"fixed64,3,opt,name=f,proto3,oneof"` // 浮点值
}

func (*ErrArg_S) isErrArg_Value() {}

func (*ErrArg_I) isErrArg_Value() {}

func (*ErrArg_F) isErrArg_Value() {}

var File_common_common_proto protoreflect.FileDescriptor

const file_common_common_proto_rawDesc = "" +
	"\n" +
	"\x13common/common.proto\x12\x06common\"?\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\"\n" +
	"\x04args\x18\x02 \x03(\v2\x0e.common.ErrArgR\x04args\"A\n" +
	"\x06ErrArg\x12\x0e\n" +
	"\x01s\x18\x01 \x01(\tH\x00R\x01s\x12\x0e\n" +
	"\x01i\x18\x02 \x01(\x03H\x00R\x01i\x12\x0e\n" +
	"\x01f\x18\x03 \x01(\x01H\x00R\x01fB\a\n" +
	"\x05valueB4Z2github.com/godyy/ggs/internal/core/proto/pb/commonb\x06proto3"

var (
	file_common_common_proto_rawDescOnce sync.Once
	file_common_common_proto_rawDescData []byte
)

func file_common_common_proto_rawDescGZIP() []byte {
	file_common_common_proto_rawDescOnce.Do(func() {
		file_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)))
	})
	return file_common_common_proto_rawDescData
}

var file_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_common_proto_goTypes = []any{
	(*Error)(nil),  // 0: common.Error
	(*ErrArg)(nil), // 1: common.ErrArg
}
var file_common_common_proto_depIdxs = []int32{
	1, // 0: common.Error.args:type_name -> common.ErrArg
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_common_proto_init() }
func file_common_common_proto_init() {
	if File_common_common_proto != nil {
		return
	}
	file_common_common_proto_msgTypes[1].OneofWrappers = []any{
		(*ErrArg_S)(nil),
		(*ErrArg_I)(nil),
		(*ErrArg_F)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_common_proto_goTypes,
		DependencyIndexes: file_common_common_proto_depIdxs,
		MessageInfos:      file_common_common_proto_msgTypes,
	}.Build()
	File_common_common_proto = out.File
	file_common_common_proto_goTypes = nil
	file_common_common_proto_depIdxs = nil
}
