// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: common/chat.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 聊天消息.
type ChatMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`               // 消息ID.
	SenderId      int64                  `protobuf:"varint,2,opt,name=senderId,proto3" json:"senderId,omitempty"`   // 发送者ID.
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`      // 聊天内容
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"` // 创建时间.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMsg) Reset() {
	*x = ChatMsg{}
	mi := &file_common_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg) ProtoMessage() {}

func (x *ChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_common_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg) Descriptor() ([]byte, []int) {
	return file_common_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMsg) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChatMsg) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ChatMsg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMsg) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 聊天室成员.
type ChatRoomMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 成员ID.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRoomMember) Reset() {
	*x = ChatRoomMember{}
	mi := &file_common_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRoomMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoomMember) ProtoMessage() {}

func (x *ChatRoomMember) ProtoReflect() protoreflect.Message {
	mi := &file_common_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoomMember.ProtoReflect.Descriptor instead.
func (*ChatRoomMember) Descriptor() ([]byte, []int) {
	return file_common_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatRoomMember) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 聊天室基础信息
type ChatRoomBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`           // 聊天室ID.
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`       // 聊天室类型.
	OwnerId       int64                  `protobuf:"varint,3,opt,name=ownerId,proto3" json:"ownerId,omitempty"` // 拥有者ID.
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`        // 聊天室名称.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRoomBase) Reset() {
	*x = ChatRoomBase{}
	mi := &file_common_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRoomBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoomBase) ProtoMessage() {}

func (x *ChatRoomBase) ProtoReflect() protoreflect.Message {
	mi := &file_common_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoomBase.ProtoReflect.Descriptor instead.
func (*ChatRoomBase) Descriptor() ([]byte, []int) {
	return file_common_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ChatRoomBase) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChatRoomBase) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ChatRoomBase) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *ChatRoomBase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 聊天室.
type ChatRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *ChatRoomBase          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`       // 聊天室基础信息.
	Members       []*ChatRoomMember      `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"` // 成员列表.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRoom) Reset() {
	*x = ChatRoom{}
	mi := &file_common_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoom) ProtoMessage() {}

func (x *ChatRoom) ProtoReflect() protoreflect.Message {
	mi := &file_common_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoom.ProtoReflect.Descriptor instead.
func (*ChatRoom) Descriptor() ([]byte, []int) {
	return file_common_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ChatRoom) GetBase() *ChatRoomBase {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ChatRoom) GetMembers() []*ChatRoomMember {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_common_chat_proto protoreflect.FileDescriptor

const file_common_chat_proto_rawDesc = "" +
	"\n" +
	"\x11common/chat.proto\x12\x06common\"m\n" +
	"\aChatMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bsenderId\x18\x02 \x01(\x03R\bsenderId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\x03R\tcreatedAt\" \n" +
	"\x0eChatRoomMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"`\n" +
	"\fChatRoomBase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x18\n" +
	"\aownerId\x18\x03 \x01(\x03R\aownerId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"f\n" +
	"\bChatRoom\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.ChatRoomBaseR\x04base\x120\n" +
	"\amembers\x18\x02 \x03(\v2\x16.common.ChatRoomMemberR\amembersB>Z<github.com/godyy/ggs/internal/infra/actor/protocol/pb/commonb\x06proto3"

var (
	file_common_chat_proto_rawDescOnce sync.Once
	file_common_chat_proto_rawDescData []byte
)

func file_common_chat_proto_rawDescGZIP() []byte {
	file_common_chat_proto_rawDescOnce.Do(func() {
		file_common_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_chat_proto_rawDesc), len(file_common_chat_proto_rawDesc)))
	})
	return file_common_chat_proto_rawDescData
}

var file_common_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_chat_proto_goTypes = []any{
	(*ChatMsg)(nil),        // 0: common.ChatMsg
	(*ChatRoomMember)(nil), // 1: common.ChatRoomMember
	(*ChatRoomBase)(nil),   // 2: common.ChatRoomBase
	(*ChatRoom)(nil),       // 3: common.ChatRoom
}
var file_common_chat_proto_depIdxs = []int32{
	2, // 0: common.ChatRoom.base:type_name -> common.ChatRoomBase
	1, // 1: common.ChatRoom.members:type_name -> common.ChatRoomMember
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_chat_proto_init() }
func file_common_chat_proto_init() {
	if File_common_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_chat_proto_rawDesc), len(file_common_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_chat_proto_goTypes,
		DependencyIndexes: file_common_chat_proto_depIdxs,
		MessageInfos:      file_common_chat_proto_msgTypes,
	}.Build()
	File_common_chat_proto = out.File
	file_common_chat_proto_goTypes = nil
	file_common_chat_proto_depIdxs = nil
}
