// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: common/error.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误码
type ErrCode int32

const (
	ErrCode_ECSuccess       ErrCode = 0 // 成功.
	ErrCode_ECInternalError ErrCode = 1 // 内部错误.
	ErrCode_ECInvalidPacket ErrCode = 2 // 无效的数据包.
	ErrCode_ECInvalidToken  ErrCode = 3 // 无效的令牌.
	ErrCode_ECLoginTimeout  ErrCode = 4 // 登陆超时.
	// 道具系统 [1000, 1999]
	ErrCode_ECItemNotEnough ErrCode = 1000 // 道具数量不足.
	// 聊天系统 [2000, 2999]
	ErrCode_ECChatRoomNotExists             ErrCode = 2000 // 聊天室不存在.
	ErrCode_ECChatRoomMemberIsSelf          ErrCode = 2001 // 成员是自己.
	ErrCode_ECChatRoomMemberEmpty           ErrCode = 2002 // 成员列表为空.
	ErrCode_ECChatRoomMemberDuplicate       ErrCode = 2003 // 成员重复.
	ErrCode_ECChatRoomMemberNotInRoom       ErrCode = 2004 // 成员不在聊天室.
	ErrCode_ECChatRoomCreateFailed          ErrCode = 2005 // 创建聊天室失败.
	ErrCode_ECChatRoomMemberAlreadyInRoom   ErrCode = 2006 // 成员已在聊天室.
	ErrCode_ECChatRoomCantLeave             ErrCode = 2007 // 不能退出聊天室.
	ErrCode_ECChatRoomMemberIsOwner         ErrCode = 2008 // 成员是群主.
	ErrCode_ECChatRoomInviteTargetEmpty     ErrCode = 2009 // 邀请目标为空.
	ErrCode_ECChatRoomInviteTargetDuplicate ErrCode = 2010 // 邀请目标重复.
	ErrCode_ECChatRoomNoPriviledge          ErrCode = 2011 // 没有权限.
	ErrCode_ECChatRoomTypeCantInvite        ErrCode = 2012 // 聊天室类型不能邀请.
	ErrCode_ECChatRoomMemberCountExceed     ErrCode = 2013 // 成员数量超过最大限制.
	ErrCode_ECChatRoomTypeInvalid           ErrCode = 2014 // 聊天室类型无效.
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:    "ECSuccess",
		1:    "ECInternalError",
		2:    "ECInvalidPacket",
		3:    "ECInvalidToken",
		4:    "ECLoginTimeout",
		1000: "ECItemNotEnough",
		2000: "ECChatRoomNotExists",
		2001: "ECChatRoomMemberIsSelf",
		2002: "ECChatRoomMemberEmpty",
		2003: "ECChatRoomMemberDuplicate",
		2004: "ECChatRoomMemberNotInRoom",
		2005: "ECChatRoomCreateFailed",
		2006: "ECChatRoomMemberAlreadyInRoom",
		2007: "ECChatRoomCantLeave",
		2008: "ECChatRoomMemberIsOwner",
		2009: "ECChatRoomInviteTargetEmpty",
		2010: "ECChatRoomInviteTargetDuplicate",
		2011: "ECChatRoomNoPriviledge",
		2012: "ECChatRoomTypeCantInvite",
		2013: "ECChatRoomMemberCountExceed",
		2014: "ECChatRoomTypeInvalid",
	}
	ErrCode_value = map[string]int32{
		"ECSuccess":                       0,
		"ECInternalError":                 1,
		"ECInvalidPacket":                 2,
		"ECInvalidToken":                  3,
		"ECLoginTimeout":                  4,
		"ECItemNotEnough":                 1000,
		"ECChatRoomNotExists":             2000,
		"ECChatRoomMemberIsSelf":          2001,
		"ECChatRoomMemberEmpty":           2002,
		"ECChatRoomMemberDuplicate":       2003,
		"ECChatRoomMemberNotInRoom":       2004,
		"ECChatRoomCreateFailed":          2005,
		"ECChatRoomMemberAlreadyInRoom":   2006,
		"ECChatRoomCantLeave":             2007,
		"ECChatRoomMemberIsOwner":         2008,
		"ECChatRoomInviteTargetEmpty":     2009,
		"ECChatRoomInviteTargetDuplicate": 2010,
		"ECChatRoomNoPriviledge":          2011,
		"ECChatRoomTypeCantInvite":        2012,
		"ECChatRoomMemberCountExceed":     2013,
		"ECChatRoomTypeInvalid":           2014,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_error_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_common_error_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_common_error_proto_rawDescGZIP(), []int{0}
}

var File_common_error_proto protoreflect.FileDescriptor

const file_common_error_proto_rawDesc = "" +
	"\n" +
	"\x12common/error.proto\x12\x06common*\xce\x04\n" +
	"\aErrCode\x12\r\n" +
	"\tECSuccess\x10\x00\x12\x13\n" +
	"\x0fECInternalError\x10\x01\x12\x13\n" +
	"\x0fECInvalidPacket\x10\x02\x12\x12\n" +
	"\x0eECInvalidToken\x10\x03\x12\x12\n" +
	"\x0eECLoginTimeout\x10\x04\x12\x14\n" +
	"\x0fECItemNotEnough\x10\xe8\a\x12\x18\n" +
	"\x13ECChatRoomNotExists\x10\xd0\x0f\x12\x1b\n" +
	"\x16ECChatRoomMemberIsSelf\x10\xd1\x0f\x12\x1a\n" +
	"\x15ECChatRoomMemberEmpty\x10\xd2\x0f\x12\x1e\n" +
	"\x19ECChatRoomMemberDuplicate\x10\xd3\x0f\x12\x1e\n" +
	"\x19ECChatRoomMemberNotInRoom\x10\xd4\x0f\x12\x1b\n" +
	"\x16ECChatRoomCreateFailed\x10\xd5\x0f\x12\"\n" +
	"\x1dECChatRoomMemberAlreadyInRoom\x10\xd6\x0f\x12\x18\n" +
	"\x13ECChatRoomCantLeave\x10\xd7\x0f\x12\x1c\n" +
	"\x17ECChatRoomMemberIsOwner\x10\xd8\x0f\x12 \n" +
	"\x1bECChatRoomInviteTargetEmpty\x10\xd9\x0f\x12$\n" +
	"\x1fECChatRoomInviteTargetDuplicate\x10\xda\x0f\x12\x1b\n" +
	"\x16ECChatRoomNoPriviledge\x10\xdb\x0f\x12\x1d\n" +
	"\x18ECChatRoomTypeCantInvite\x10\xdc\x0f\x12 \n" +
	"\x1bECChatRoomMemberCountExceed\x10\xdd\x0f\x12\x1a\n" +
	"\x15ECChatRoomTypeInvalid\x10\xde\x0fB>Z<github.com/godyy/ggs/internal/infra/actor/protocol/pb/commonb\x06proto3"

var (
	file_common_error_proto_rawDescOnce sync.Once
	file_common_error_proto_rawDescData []byte
)

func file_common_error_proto_rawDescGZIP() []byte {
	file_common_error_proto_rawDescOnce.Do(func() {
		file_common_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_error_proto_rawDesc), len(file_common_error_proto_rawDesc)))
	})
	return file_common_error_proto_rawDescData
}

var file_common_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_error_proto_goTypes = []any{
	(ErrCode)(0), // 0: common.ErrCode
}
var file_common_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_error_proto_init() }
func file_common_error_proto_init() {
	if File_common_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_error_proto_rawDesc), len(file_common_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_error_proto_goTypes,
		DependencyIndexes: file_common_error_proto_depIdxs,
		EnumInfos:         file_common_error_proto_enumTypes,
	}.Build()
	File_common_error_proto = out.File
	file_common_error_proto_goTypes = nil
	file_common_error_proto_depIdxs = nil
}
