// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: c2s/chat.proto

package c2s

import (
	common "github.com/godyy/ggs/internal/infra/actor/protocol/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送聊天消息请求.
type SendChatMsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`  // 聊天室ID.
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 聊天内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChatMsgReq) Reset() {
	*x = SendChatMsgReq{}
	mi := &file_c2s_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatMsgReq) ProtoMessage() {}

func (x *SendChatMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatMsgReq.ProtoReflect.Descriptor instead.
func (*SendChatMsgReq) Descriptor() ([]byte, []int) {
	return file_c2s_chat_proto_rawDescGZIP(), []int{0}
}

func (x *SendChatMsgReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *SendChatMsgReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 获取聊天历史请求.
type ChatHistoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`       // 聊天室ID.
	LastMsgId     int64                  `protobuf:"varint,2,opt,name=lastMsgId,proto3" json:"lastMsgId,omitempty"` // 最后一条消息ID.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatHistoryReq) Reset() {
	*x = ChatHistoryReq{}
	mi := &file_c2s_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatHistoryReq) ProtoMessage() {}

func (x *ChatHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatHistoryReq.ProtoReflect.Descriptor instead.
func (*ChatHistoryReq) Descriptor() ([]byte, []int) {
	return file_c2s_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatHistoryReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ChatHistoryReq) GetLastMsgId() int64 {
	if x != nil {
		return x.LastMsgId
	}
	return 0
}

// 获取聊天历史响应.
type ChatHistoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"` // 聊天室ID.
	Msgs          []*common.ChatMsg      `protobuf:"bytes,2,rep,name=msgs,proto3" json:"msgs,omitempty"`      // 聊天消息列表.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatHistoryResp) Reset() {
	*x = ChatHistoryResp{}
	mi := &file_c2s_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatHistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatHistoryResp) ProtoMessage() {}

func (x *ChatHistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatHistoryResp.ProtoReflect.Descriptor instead.
func (*ChatHistoryResp) Descriptor() ([]byte, []int) {
	return file_c2s_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ChatHistoryResp) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ChatHistoryResp) GetMsgs() []*common.ChatMsg {
	if x != nil {
		return x.Msgs
	}
	return nil
}

// 聊天消息推送.
type ChatMsgPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"` // 聊天室ID
	Msg           *common.ChatMsg        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`        // 聊天消息.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMsgPush) Reset() {
	*x = ChatMsgPush{}
	mi := &file_c2s_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMsgPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsgPush) ProtoMessage() {}

func (x *ChatMsgPush) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsgPush.ProtoReflect.Descriptor instead.
func (*ChatMsgPush) Descriptor() ([]byte, []int) {
	return file_c2s_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ChatMsgPush) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ChatMsgPush) GetMsg() *common.ChatMsg {
	if x != nil {
		return x.Msg
	}
	return nil
}

// 创建群组聊天室请求.
type CreateGroupChatRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                   // 群组名称.
	MemberIds     []int64                `protobuf:"varint,2,rep,packed,name=memberIds,proto3" json:"memberIds,omitempty"` // 成员ID列表.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupChatRoomReq) Reset() {
	*x = CreateGroupChatRoomReq{}
	mi := &file_c2s_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupChatRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupChatRoomReq) ProtoMessage() {}

func (x *CreateGroupChatRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupChatRoomReq.ProtoReflect.Descriptor instead.
func (*CreateGroupChatRoomReq) Descriptor() ([]byte, []int) {
	return file_c2s_chat_proto_rawDescGZIP(), []int{4}
}

func (x *CreateGroupChatRoomReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupChatRoomReq) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

// 加入聊天室推送.
type JoinChatRoomPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *common.ChatRoom       `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"` // 聊天室.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinChatRoomPush) Reset() {
	*x = JoinChatRoomPush{}
	mi := &file_c2s_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinChatRoomPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinChatRoomPush) ProtoMessage() {}

func (x *JoinChatRoomPush) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinChatRoomPush.ProtoReflect.Descriptor instead.
func (*JoinChatRoomPush) Descriptor() ([]byte, []int) {
	return file_c2s_chat_proto_rawDescGZIP(), []int{5}
}

func (x *JoinChatRoomPush) GetRoom() *common.ChatRoom {
	if x != nil {
		return x.Room
	}
	return nil
}

// 聊天室成员加入推送.
type ChatRoomMemberJoinPush struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	RoomId        int64                    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`        // 聊天室ID.
	NewMembers    []*common.ChatRoomMember `protobuf:"bytes,2,rep,name=newMembers,proto3" json:"newMembers,omitempty"` // 新成员列表.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRoomMemberJoinPush) Reset() {
	*x = ChatRoomMemberJoinPush{}
	mi := &file_c2s_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRoomMemberJoinPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoomMemberJoinPush) ProtoMessage() {}

func (x *ChatRoomMemberJoinPush) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoomMemberJoinPush.ProtoReflect.Descriptor instead.
func (*ChatRoomMemberJoinPush) Descriptor() ([]byte, []int) {
	return file_c2s_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ChatRoomMemberJoinPush) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ChatRoomMemberJoinPush) GetNewMembers() []*common.ChatRoomMember {
	if x != nil {
		return x.NewMembers
	}
	return nil
}

// 退出聊天室请求.
type LeaveChatRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"` // 聊天室ID.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveChatRoomReq) Reset() {
	*x = LeaveChatRoomReq{}
	mi := &file_c2s_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveChatRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveChatRoomReq) ProtoMessage() {}

func (x *LeaveChatRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveChatRoomReq.ProtoReflect.Descriptor instead.
func (*LeaveChatRoomReq) Descriptor() ([]byte, []int) {
	return file_c2s_chat_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveChatRoomReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

// 退出聊天室响应.
type LeaveChatRoomResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"` // 聊天室ID.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveChatRoomResp) Reset() {
	*x = LeaveChatRoomResp{}
	mi := &file_c2s_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveChatRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveChatRoomResp) ProtoMessage() {}

func (x *LeaveChatRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveChatRoomResp.ProtoReflect.Descriptor instead.
func (*LeaveChatRoomResp) Descriptor() ([]byte, []int) {
	return file_c2s_chat_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveChatRoomResp) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

// 聊天室成员退出推送.
type ChatRoomMemberLeavePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`              // 聊天室ID.
	MemberIds     []int64                `protobuf:"varint,2,rep,packed,name=memberIds,proto3" json:"memberIds,omitempty"` // 成员ID.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRoomMemberLeavePush) Reset() {
	*x = ChatRoomMemberLeavePush{}
	mi := &file_c2s_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRoomMemberLeavePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoomMemberLeavePush) ProtoMessage() {}

func (x *ChatRoomMemberLeavePush) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoomMemberLeavePush.ProtoReflect.Descriptor instead.
func (*ChatRoomMemberLeavePush) Descriptor() ([]byte, []int) {
	return file_c2s_chat_proto_rawDescGZIP(), []int{9}
}

func (x *ChatRoomMemberLeavePush) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ChatRoomMemberLeavePush) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

// 邀请玩家加入聊天室请求.
type ChatRoomInviteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`              // 聊天室ID.
	TargetIds     []int64                `protobuf:"varint,2,rep,packed,name=targetIds,proto3" json:"targetIds,omitempty"` // 目标玩家ID列表.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRoomInviteReq) Reset() {
	*x = ChatRoomInviteReq{}
	mi := &file_c2s_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRoomInviteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoomInviteReq) ProtoMessage() {}

func (x *ChatRoomInviteReq) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoomInviteReq.ProtoReflect.Descriptor instead.
func (*ChatRoomInviteReq) Descriptor() ([]byte, []int) {
	return file_c2s_chat_proto_rawDescGZIP(), []int{10}
}

func (x *ChatRoomInviteReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ChatRoomInviteReq) GetTargetIds() []int64 {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

var File_c2s_chat_proto protoreflect.FileDescriptor

const file_c2s_chat_proto_rawDesc = "" +
	"\n" +
	"\x0ec2s/chat.proto\x12\x03c2s\x1a\x11common/chat.proto\"B\n" +
	"\x0eSendChatMsgReq\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x03R\x06roomId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"F\n" +
	"\x0eChatHistoryReq\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x03R\x06roomId\x12\x1c\n" +
	"\tlastMsgId\x18\x02 \x01(\x03R\tlastMsgId\"N\n" +
	"\x0fChatHistoryResp\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x03R\x06roomId\x12#\n" +
	"\x04msgs\x18\x02 \x03(\v2\x0f.common.ChatMsgR\x04msgs\"H\n" +
	"\vChatMsgPush\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x03R\x06roomId\x12!\n" +
	"\x03msg\x18\x02 \x01(\v2\x0f.common.ChatMsgR\x03msg\"J\n" +
	"\x16CreateGroupChatRoomReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tmemberIds\x18\x02 \x03(\x03R\tmemberIds\"8\n" +
	"\x10JoinChatRoomPush\x12$\n" +
	"\x04room\x18\x01 \x01(\v2\x10.common.ChatRoomR\x04room\"h\n" +
	"\x16ChatRoomMemberJoinPush\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x03R\x06roomId\x126\n" +
	"\n" +
	"newMembers\x18\x02 \x03(\v2\x16.common.ChatRoomMemberR\n" +
	"newMembers\"*\n" +
	"\x10LeaveChatRoomReq\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x03R\x06roomId\"+\n" +
	"\x11LeaveChatRoomResp\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x03R\x06roomId\"O\n" +
	"\x17ChatRoomMemberLeavePush\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x03R\x06roomId\x12\x1c\n" +
	"\tmemberIds\x18\x02 \x03(\x03R\tmemberIds\"I\n" +
	"\x11ChatRoomInviteReq\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x03R\x06roomId\x12\x1c\n" +
	"\ttargetIds\x18\x02 \x03(\x03R\ttargetIdsB;Z9github.com/godyy/ggs/internal/infra/actor/protocol/pb/c2sb\x06proto3"

var (
	file_c2s_chat_proto_rawDescOnce sync.Once
	file_c2s_chat_proto_rawDescData []byte
)

func file_c2s_chat_proto_rawDescGZIP() []byte {
	file_c2s_chat_proto_rawDescOnce.Do(func() {
		file_c2s_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_c2s_chat_proto_rawDesc), len(file_c2s_chat_proto_rawDesc)))
	})
	return file_c2s_chat_proto_rawDescData
}

var file_c2s_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_c2s_chat_proto_goTypes = []any{
	(*SendChatMsgReq)(nil),          // 0: c2s.SendChatMsgReq
	(*ChatHistoryReq)(nil),          // 1: c2s.ChatHistoryReq
	(*ChatHistoryResp)(nil),         // 2: c2s.ChatHistoryResp
	(*ChatMsgPush)(nil),             // 3: c2s.ChatMsgPush
	(*CreateGroupChatRoomReq)(nil),  // 4: c2s.CreateGroupChatRoomReq
	(*JoinChatRoomPush)(nil),        // 5: c2s.JoinChatRoomPush
	(*ChatRoomMemberJoinPush)(nil),  // 6: c2s.ChatRoomMemberJoinPush
	(*LeaveChatRoomReq)(nil),        // 7: c2s.LeaveChatRoomReq
	(*LeaveChatRoomResp)(nil),       // 8: c2s.LeaveChatRoomResp
	(*ChatRoomMemberLeavePush)(nil), // 9: c2s.ChatRoomMemberLeavePush
	(*ChatRoomInviteReq)(nil),       // 10: c2s.ChatRoomInviteReq
	(*common.ChatMsg)(nil),          // 11: common.ChatMsg
	(*common.ChatRoom)(nil),         // 12: common.ChatRoom
	(*common.ChatRoomMember)(nil),   // 13: common.ChatRoomMember
}
var file_c2s_chat_proto_depIdxs = []int32{
	11, // 0: c2s.ChatHistoryResp.msgs:type_name -> common.ChatMsg
	11, // 1: c2s.ChatMsgPush.msg:type_name -> common.ChatMsg
	12, // 2: c2s.JoinChatRoomPush.room:type_name -> common.ChatRoom
	13, // 3: c2s.ChatRoomMemberJoinPush.newMembers:type_name -> common.ChatRoomMember
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_c2s_chat_proto_init() }
func file_c2s_chat_proto_init() {
	if File_c2s_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_c2s_chat_proto_rawDesc), len(file_c2s_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_c2s_chat_proto_goTypes,
		DependencyIndexes: file_c2s_chat_proto_depIdxs,
		MessageInfos:      file_c2s_chat_proto_msgTypes,
	}.Build()
	File_c2s_chat_proto = out.File
	file_c2s_chat_proto_goTypes = nil
	file_c2s_chat_proto_depIdxs = nil
}
