// Code generated by proto/tools/gen_register; DO NOT EDIT.
// 该文件由工具生成，请勿手动编辑。

package c2s

import (
	"github.com/godyy/ggs/internal/infra/actor/protocol/pb/c2s"
	"github.com/godyy/ggs/internal/infra/actor/protocol/pb/common"
)

func init() {
	register((*common.Error)(nil))
	register((*common.Success)(nil))
	register((*c2s.ChatHistoryReq)(nil))
	register((*c2s.ChatHistoryResp)(nil))
	register((*c2s.ChatMsgPush)(nil))
	register((*c2s.ChatRoomInviteReq)(nil))
	register((*c2s.ChatRoomMemberJoinPush)(nil))
	register((*c2s.ChatRoomMemberLeavePush)(nil))
	register((*c2s.CreateGroupChatRoomReq)(nil))
	register((*c2s.DisconnectPush)(nil))
	register((*c2s.HeartbeatReq)(nil))
	register((*c2s.HeartbeatResp)(nil))
	register((*c2s.ItemPush)(nil))
	register((*c2s.JoinChatRoomPush)(nil))
	register((*c2s.LeaveChatRoomReq)(nil))
	register((*c2s.LeaveChatRoomResp)(nil))
	register((*c2s.LoginCharacterReq)(nil))
	register((*c2s.LoginCharacterResp)(nil))
	register((*c2s.LoginReq)(nil))
	register((*c2s.LoginResp)(nil))
	register((*c2s.ModifyNameReq)(nil))
	register((*c2s.ModifyNameResp)(nil))
	register((*c2s.SendChatMsgReq)(nil))
	register((*c2s.UseItemReq)(nil))
	register((*c2s.UseItemResp)(nil))
}
