package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	pkgerrors "github.com/pkg/errors"
)

// pbPkgPathRoot 导出Pb文件库的根路径.
const pbPkgPathRoot = "github.com/godyy/ggs/internal/infra/actor/protocol/pb/"

// pbCommonPath 导出common Pb的路径.
const pbCommonPath = "common"

var registrableMessageSuffixes = []string{"Req", "Resp", "Push", "Ntf"}

type commonTarget uint8

const (
	commonTargetC2S commonTarget = 1 << iota
	commonTargetS2S
)

type commonMessageRegistration struct {
	Name   string
	Target commonTarget
}

var commonMessageRegistrations = []commonMessageRegistration{
	{Name: "Error", Target: commonTargetC2S | commonTargetS2S},
}

func isRegistrableMessageName(name string) bool {
	for _, suffix := range registrableMessageSuffixes {
		if strings.HasSuffix(name, suffix) {
			return true
		}
	}
	return false
}

func commonMessagesFor(target commonTarget) []string {
	var names []string
	for _, reg := range commonMessageRegistrations {
		if reg.Target&target != 0 {
			names = append(names, reg.Name)
		}
	}
	sort.Strings(names)
	return names
}

func parseProtoMessageNames(protoPath string) ([]string, error) {
	data, err := os.ReadFile(protoPath)
	if err != nil {
		return nil, pkgerrors.WithMessagef(err, "read proto %s", protoPath)
	}

	src := string(data)
	re := regexp.MustCompile(`(?m)^message\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{`)
	matches := re.FindAllStringSubmatch(src, -1)

	names := make([]string, 0, len(matches))
	for _, m := range matches {
		if len(m) < 2 {
			continue
		}
		names = append(names, m[1])
	}
	return names, nil
}

func parseRegistrableMessageNamesInDir(protoDir string) ([]string, error) {
	entries, err := os.ReadDir(protoDir)
	if err != nil {
		return nil, pkgerrors.WithMessagef(err, "read proto dir %s", protoDir)
	}

	var protoFiles []string
	for _, ent := range entries {
		if ent.IsDir() {
			continue
		}
		if strings.HasSuffix(ent.Name(), ".proto") {
			protoFiles = append(protoFiles, filepath.Join(protoDir, ent.Name()))
		}
	}
	sort.Strings(protoFiles)

	seen := make(map[string]struct{}, 64)
	var names []string
	for _, f := range protoFiles {
		msgNames, err := parseProtoMessageNames(f)
		if err != nil {
			return nil, err
		}
		for _, name := range msgNames {
			if !isRegistrableMessageName(name) {
				continue
			}
			if _, ok := seen[name]; ok {
				continue
			}
			seen[name] = struct{}{}
			names = append(names, name)
		}
	}
	sort.Strings(names)
	return names, nil
}

func generateRegisterFile(registryPkg string, pbPkgPath string, msgNames []string, commonMsgNames []string) ([]byte, error) {
	var buf bytes.Buffer
	// Add do-not-edit banner
	buf.WriteString("// Code generated by proto/tools/gen_register; DO NOT EDIT.\n")
	buf.WriteString("// 该文件由工具生成，请勿手动编辑。\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", registryPkg))

	needCommon := len(commonMsgNames) > 0
	// compose full import path from root + relative pkgPath
	pkgImport := path.Join(pbPkgPathRoot, pbPkgPath)
	// derive package name prefix from basename of pbPkgPath
	pkgName := path.Base(pbPkgPath)
	if needCommon {
		buf.WriteString("import (\n")
		buf.WriteString(fmt.Sprintf("\t\"%s\"\n", pkgImport))
		buf.WriteString(fmt.Sprintf("\t\"%s\"\n", path.Join(pbPkgPathRoot, pbCommonPath)))
		buf.WriteString(")\n\n")
	} else {
		buf.WriteString(fmt.Sprintf("import \"%s\"\n\n", pkgImport))
	}
	buf.WriteString("func init() {\n")
	for _, name := range commonMsgNames {
		buf.WriteString(fmt.Sprintf("\tregister((*common.%s)(nil))\n", name))
	}
	for _, name := range msgNames {
		buf.WriteString(fmt.Sprintf("\tregister((*%s.%s)(nil))\n", pkgName, name))
	}
	buf.WriteString("}\n")

	// format the code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// return unformatted to help diagnose formatting errors
		return buf.Bytes(), pkgerrors.WithMessage(err, "format generated code")
	}
	return formatted, nil
}

func main() {
	// Require proto root via flag (no fallback to exePath)
	protoRoot := flag.String("proto-path", "", "path to proto root directory (e.g., /Users/you/work/ggs/app/internal/protocol)")
	flag.Parse()
	if *protoRoot == "" {
		panic(fmt.Errorf("missing -proto-path flag: set path to ggs/internal/infra/actor/protocol"))
	}

	registryDir := filepath.Join(*protoRoot, "registry")
	protoDir := filepath.Join(*protoRoot, "protos")
	c2sProtoDir := filepath.Join(protoDir, "c2s")
	s2sProtoDir := filepath.Join(protoDir, "s2s")

	c2sMsgNames, err := parseRegistrableMessageNamesInDir(c2sProtoDir)
	if err != nil {
		panic(err)
	}
	s2sMsgNames, err := parseRegistrableMessageNamesInDir(s2sProtoDir)
	if err != nil {
		panic(err)
	}

	// Generate files
	c2sCode, err := generateRegisterFile(
		"c2s",
		"c2s",
		c2sMsgNames,
		commonMessagesFor(commonTargetC2S),
	)
	if err != nil {
		panic(err)
	}
	s2sCode, err := generateRegisterFile(
		"s2s",
		"s2s",
		s2sMsgNames,
		commonMessagesFor(commonTargetS2S),
	)
	if err != nil {
		panic(err)
	}

	// Write outputs
	if err := os.WriteFile(filepath.Join(registryDir, "c2s", "register.go"), c2sCode, 0o644); err != nil {
		panic(err)
	}
	if err := os.WriteFile(filepath.Join(registryDir, "s2s", "register.go"), s2sCode, 0o644); err != nil {
		panic(err)
	}
}
