// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: s2s/chat.proto

package s2s

import (
	common "github.com/godyy/ggs/internal/infra/actor/protocol/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送聊天消息请求.
type SendChatMsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`     // 聊天室ID.
	SenderId      int64                  `protobuf:"varint,2,opt,name=senderId,proto3" json:"senderId,omitempty"` // 发送者ID.
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`    // 聊天内容.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChatMsgReq) Reset() {
	*x = SendChatMsgReq{}
	mi := &file_s2s_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatMsgReq) ProtoMessage() {}

func (x *SendChatMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_s2s_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatMsgReq.ProtoReflect.Descriptor instead.
func (*SendChatMsgReq) Descriptor() ([]byte, []int) {
	return file_s2s_chat_proto_rawDescGZIP(), []int{0}
}

func (x *SendChatMsgReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *SendChatMsgReq) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendChatMsgReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 创建群组聊天室请求.
type CreateGroupChatRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                   // 群组名称.
	MemberIds     []int64                `protobuf:"varint,2,rep,packed,name=memberIds,proto3" json:"memberIds,omitempty"` // 成员ID列表. 第一个成员为群主.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupChatRoomReq) Reset() {
	*x = CreateGroupChatRoomReq{}
	mi := &file_s2s_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupChatRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupChatRoomReq) ProtoMessage() {}

func (x *CreateGroupChatRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_s2s_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupChatRoomReq.ProtoReflect.Descriptor instead.
func (*CreateGroupChatRoomReq) Descriptor() ([]byte, []int) {
	return file_s2s_chat_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGroupChatRoomReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupChatRoomReq) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

// 通知加入聊天室请求.
type NotifyJoinChatRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`     // 聊天室ID.
	RoomType      int32                  `protobuf:"varint,2,opt,name=roomType,proto3" json:"roomType,omitempty"` // 聊天室类型.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyJoinChatRoomReq) Reset() {
	*x = NotifyJoinChatRoomReq{}
	mi := &file_s2s_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyJoinChatRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyJoinChatRoomReq) ProtoMessage() {}

func (x *NotifyJoinChatRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_s2s_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyJoinChatRoomReq.ProtoReflect.Descriptor instead.
func (*NotifyJoinChatRoomReq) Descriptor() ([]byte, []int) {
	return file_s2s_chat_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyJoinChatRoomReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *NotifyJoinChatRoomReq) GetRoomType() int32 {
	if x != nil {
		return x.RoomType
	}
	return 0
}

// 加入聊天室请求.
type JoinChatRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *common.ChatRoom       `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"` // 聊天室.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinChatRoomReq) Reset() {
	*x = JoinChatRoomReq{}
	mi := &file_s2s_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinChatRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinChatRoomReq) ProtoMessage() {}

func (x *JoinChatRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_s2s_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinChatRoomReq.ProtoReflect.Descriptor instead.
func (*JoinChatRoomReq) Descriptor() ([]byte, []int) {
	return file_s2s_chat_proto_rawDescGZIP(), []int{3}
}

func (x *JoinChatRoomReq) GetRoom() *common.ChatRoom {
	if x != nil {
		return x.Room
	}
	return nil
}

// 退出聊天室请求.
type LeaveChatRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`     // 聊天室ID.
	MemberId      int64                  `protobuf:"varint,2,opt,name=memberId,proto3" json:"memberId,omitempty"` // 成员ID.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveChatRoomReq) Reset() {
	*x = LeaveChatRoomReq{}
	mi := &file_s2s_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveChatRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveChatRoomReq) ProtoMessage() {}

func (x *LeaveChatRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_s2s_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveChatRoomReq.ProtoReflect.Descriptor instead.
func (*LeaveChatRoomReq) Descriptor() ([]byte, []int) {
	return file_s2s_chat_proto_rawDescGZIP(), []int{4}
}

func (x *LeaveChatRoomReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *LeaveChatRoomReq) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

// 通知退出聊天室请求.
type NotifyLeaveChatRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"` // 聊天室ID.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyLeaveChatRoomReq) Reset() {
	*x = NotifyLeaveChatRoomReq{}
	mi := &file_s2s_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyLeaveChatRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyLeaveChatRoomReq) ProtoMessage() {}

func (x *NotifyLeaveChatRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_s2s_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyLeaveChatRoomReq.ProtoReflect.Descriptor instead.
func (*NotifyLeaveChatRoomReq) Descriptor() ([]byte, []int) {
	return file_s2s_chat_proto_rawDescGZIP(), []int{5}
}

func (x *NotifyLeaveChatRoomReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

// 邀请玩家加入聊天室请求.
type ChatRoomInviteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`              // 聊天室ID.
	InviterId     int64                  `protobuf:"varint,2,opt,name=inviterId,proto3" json:"inviterId,omitempty"`        // 邀请者ID.
	TargetIds     []int64                `protobuf:"varint,3,rep,packed,name=targetIds,proto3" json:"targetIds,omitempty"` // 目标玩家ID列表.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRoomInviteReq) Reset() {
	*x = ChatRoomInviteReq{}
	mi := &file_s2s_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRoomInviteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoomInviteReq) ProtoMessage() {}

func (x *ChatRoomInviteReq) ProtoReflect() protoreflect.Message {
	mi := &file_s2s_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoomInviteReq.ProtoReflect.Descriptor instead.
func (*ChatRoomInviteReq) Descriptor() ([]byte, []int) {
	return file_s2s_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ChatRoomInviteReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ChatRoomInviteReq) GetInviterId() int64 {
	if x != nil {
		return x.InviterId
	}
	return 0
}

func (x *ChatRoomInviteReq) GetTargetIds() []int64 {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

// 获取聊天历史请求.
type ChatHistoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      int64                  `protobuf:"varint,1,opt,name=memberId,proto3" json:"memberId,omitempty"`   // 成员ID.
	RoomId        int64                  `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`       // 聊天室ID.
	LastMsgId     int64                  `protobuf:"varint,3,opt,name=lastMsgId,proto3" json:"lastMsgId,omitempty"` // 最后一条消息ID.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatHistoryReq) Reset() {
	*x = ChatHistoryReq{}
	mi := &file_s2s_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatHistoryReq) ProtoMessage() {}

func (x *ChatHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_s2s_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatHistoryReq.ProtoReflect.Descriptor instead.
func (*ChatHistoryReq) Descriptor() ([]byte, []int) {
	return file_s2s_chat_proto_rawDescGZIP(), []int{7}
}

func (x *ChatHistoryReq) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *ChatHistoryReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ChatHistoryReq) GetLastMsgId() int64 {
	if x != nil {
		return x.LastMsgId
	}
	return 0
}

// 获取聊天历史响应.
type ChatHistoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"` // 聊天室ID.
	Msgs          []*common.ChatMsg      `protobuf:"bytes,2,rep,name=msgs,proto3" json:"msgs,omitempty"`      // 聊天消息列表.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatHistoryResp) Reset() {
	*x = ChatHistoryResp{}
	mi := &file_s2s_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatHistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatHistoryResp) ProtoMessage() {}

func (x *ChatHistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_s2s_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatHistoryResp.ProtoReflect.Descriptor instead.
func (*ChatHistoryResp) Descriptor() ([]byte, []int) {
	return file_s2s_chat_proto_rawDescGZIP(), []int{8}
}

func (x *ChatHistoryResp) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ChatHistoryResp) GetMsgs() []*common.ChatMsg {
	if x != nil {
		return x.Msgs
	}
	return nil
}

var File_s2s_chat_proto protoreflect.FileDescriptor

const file_s2s_chat_proto_rawDesc = "" +
	"\n" +
	"\x0es2s/chat.proto\x12\x03s2s\x1a\x11common/chat.proto\"^\n" +
	"\x0eSendChatMsgReq\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x03R\x06roomId\x12\x1a\n" +
	"\bsenderId\x18\x02 \x01(\x03R\bsenderId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"J\n" +
	"\x16CreateGroupChatRoomReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tmemberIds\x18\x02 \x03(\x03R\tmemberIds\"K\n" +
	"\x15NotifyJoinChatRoomReq\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x03R\x06roomId\x12\x1a\n" +
	"\broomType\x18\x02 \x01(\x05R\broomType\"7\n" +
	"\x0fJoinChatRoomReq\x12$\n" +
	"\x04room\x18\x01 \x01(\v2\x10.common.ChatRoomR\x04room\"F\n" +
	"\x10LeaveChatRoomReq\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x03R\x06roomId\x12\x1a\n" +
	"\bmemberId\x18\x02 \x01(\x03R\bmemberId\"0\n" +
	"\x16NotifyLeaveChatRoomReq\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x03R\x06roomId\"g\n" +
	"\x11ChatRoomInviteReq\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x03R\x06roomId\x12\x1c\n" +
	"\tinviterId\x18\x02 \x01(\x03R\tinviterId\x12\x1c\n" +
	"\ttargetIds\x18\x03 \x03(\x03R\ttargetIds\"b\n" +
	"\x0eChatHistoryReq\x12\x1a\n" +
	"\bmemberId\x18\x01 \x01(\x03R\bmemberId\x12\x16\n" +
	"\x06roomId\x18\x02 \x01(\x03R\x06roomId\x12\x1c\n" +
	"\tlastMsgId\x18\x03 \x01(\x03R\tlastMsgId\"N\n" +
	"\x0fChatHistoryResp\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x03R\x06roomId\x12#\n" +
	"\x04msgs\x18\x02 \x03(\v2\x0f.common.ChatMsgR\x04msgsB;Z9github.com/godyy/ggs/internal/infra/actor/protocol/pb/s2sb\x06proto3"

var (
	file_s2s_chat_proto_rawDescOnce sync.Once
	file_s2s_chat_proto_rawDescData []byte
)

func file_s2s_chat_proto_rawDescGZIP() []byte {
	file_s2s_chat_proto_rawDescOnce.Do(func() {
		file_s2s_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_s2s_chat_proto_rawDesc), len(file_s2s_chat_proto_rawDesc)))
	})
	return file_s2s_chat_proto_rawDescData
}

var file_s2s_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_s2s_chat_proto_goTypes = []any{
	(*SendChatMsgReq)(nil),         // 0: s2s.SendChatMsgReq
	(*CreateGroupChatRoomReq)(nil), // 1: s2s.CreateGroupChatRoomReq
	(*NotifyJoinChatRoomReq)(nil),  // 2: s2s.NotifyJoinChatRoomReq
	(*JoinChatRoomReq)(nil),        // 3: s2s.JoinChatRoomReq
	(*LeaveChatRoomReq)(nil),       // 4: s2s.LeaveChatRoomReq
	(*NotifyLeaveChatRoomReq)(nil), // 5: s2s.NotifyLeaveChatRoomReq
	(*ChatRoomInviteReq)(nil),      // 6: s2s.ChatRoomInviteReq
	(*ChatHistoryReq)(nil),         // 7: s2s.ChatHistoryReq
	(*ChatHistoryResp)(nil),        // 8: s2s.ChatHistoryResp
	(*common.ChatRoom)(nil),        // 9: common.ChatRoom
	(*common.ChatMsg)(nil),         // 10: common.ChatMsg
}
var file_s2s_chat_proto_depIdxs = []int32{
	9,  // 0: s2s.JoinChatRoomReq.room:type_name -> common.ChatRoom
	10, // 1: s2s.ChatHistoryResp.msgs:type_name -> common.ChatMsg
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_s2s_chat_proto_init() }
func file_s2s_chat_proto_init() {
	if File_s2s_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s2s_chat_proto_rawDesc), len(file_s2s_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_s2s_chat_proto_goTypes,
		DependencyIndexes: file_s2s_chat_proto_depIdxs,
		MessageInfos:      file_s2s_chat_proto_msgTypes,
	}.Build()
	File_s2s_chat_proto = out.File
	file_s2s_chat_proto_goTypes = nil
	file_s2s_chat_proto_depIdxs = nil
}
