// Code generated by proto/tools/gen_register; DO NOT EDIT.
// 该文件由工具生成，请勿手动编辑。

package types

import (
	"github.com/godyy/ggs/internal/proto/pb/c2s"
	"github.com/godyy/ggs/internal/proto/pb/common"
)

func init() {
	C2S.register(c2s.PID_PError, &common.Error{})
	C2S.register(c2s.PID_PLoginReq, &c2s.LoginReq{})
	C2S.register(c2s.PID_PLoginResp, &c2s.LoginResp{})
	C2S.register(c2s.PID_PLoginCharacterReq, &c2s.LoginCharacterReq{})
	C2S.register(c2s.PID_PLoginCharacterResp, &c2s.LoginCharacterResp{})
	C2S.register(c2s.PID_PDisconnectPush, &c2s.DisconnectPush{})
	C2S.register(c2s.PID_PHeartbeatReq, &c2s.HeartbeatReq{})
	C2S.register(c2s.PID_PHeartbeatResp, &c2s.HeartbeatResp{})
	C2S.register(c2s.PID_PModifyNameReq, &c2s.ModifyNameReq{})
	C2S.register(c2s.PID_PModifyNameResp, &c2s.ModifyNameResp{})
}
