// Code generated by proto/tools/gen_register; DO NOT EDIT.
// 该文件由工具生成，请勿手动编辑。

package types

import (
	"github.com/godyy/ggs/internal/proto/pb/common"
	"github.com/godyy/ggs/internal/proto/pb/s2s"
)

func init() {
	S2S.register(s2s.PID_PError, &common.Error{})
	S2S.register(s2s.PID_PActorSaveResult, &s2s.ActorSaveResult{})
}
