// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: c2s/error.proto

package c2s

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误码.
type ErrCode int32

const (
	ErrCode_ECSuccess       ErrCode = 0 // 成功.
	ErrCode_ECInternalError ErrCode = 1 // 内部错误.
	ErrCode_ECInvalidPacket ErrCode = 2 // 无效的数据包.
	ErrCode_ECInvalidToken  ErrCode = 3 // 无效的令牌.
	ErrCode_ECLoginTimeout  ErrCode = 4 // 登陆超时.
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0: "ECSuccess",
		1: "ECInternalError",
		2: "ECInvalidPacket",
		3: "ECInvalidToken",
		4: "ECLoginTimeout",
	}
	ErrCode_value = map[string]int32{
		"ECSuccess":       0,
		"ECInternalError": 1,
		"ECInvalidPacket": 2,
		"ECInvalidToken":  3,
		"ECLoginTimeout":  4,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_c2s_error_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_c2s_error_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_c2s_error_proto_rawDescGZIP(), []int{0}
}

var File_c2s_error_proto protoreflect.FileDescriptor

const file_c2s_error_proto_rawDesc = "" +
	"\n" +
	"\x0fc2s/error.proto\x12\x03c2s*j\n" +
	"\aErrCode\x12\r\n" +
	"\tECSuccess\x10\x00\x12\x13\n" +
	"\x0fECInternalError\x10\x01\x12\x13\n" +
	"\x0fECInvalidPacket\x10\x02\x12\x12\n" +
	"\x0eECInvalidToken\x10\x03\x12\x12\n" +
	"\x0eECLoginTimeout\x10\x04B1Z/github.com/godyy/ggs/internal/core/proto/pb/c2sb\x06proto3"

var (
	file_c2s_error_proto_rawDescOnce sync.Once
	file_c2s_error_proto_rawDescData []byte
)

func file_c2s_error_proto_rawDescGZIP() []byte {
	file_c2s_error_proto_rawDescOnce.Do(func() {
		file_c2s_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_c2s_error_proto_rawDesc), len(file_c2s_error_proto_rawDesc)))
	})
	return file_c2s_error_proto_rawDescData
}

var file_c2s_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_c2s_error_proto_goTypes = []any{
	(ErrCode)(0), // 0: c2s.ErrCode
}
var file_c2s_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_c2s_error_proto_init() }
func file_c2s_error_proto_init() {
	if File_c2s_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_c2s_error_proto_rawDesc), len(file_c2s_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_c2s_error_proto_goTypes,
		DependencyIndexes: file_c2s_error_proto_depIdxs,
		EnumInfos:         file_c2s_error_proto_enumTypes,
	}.Build()
	File_c2s_error_proto = out.File
	file_c2s_error_proto_goTypes = nil
	file_c2s_error_proto_depIdxs = nil
}
