// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: c2s/login.proto

package c2s

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DisconnectPush_Reason int32

const (
	DisconnectPush_Unknown      DisconnectPush_Reason = 0 // 未知.
	DisconnectPush_SystemError  DisconnectPush_Reason = 1 // 系统错误.
	DisconnectPush_Disconnect   DisconnectPush_Reason = 2 // 被断开.
	DisconnectPush_AnotherLogin DisconnectPush_Reason = 3 // 另一个登录.
	DisconnectPush_LoginTimeout DisconnectPush_Reason = 4 // 登录超时.
)

// Enum value maps for DisconnectPush_Reason.
var (
	DisconnectPush_Reason_name = map[int32]string{
		0: "Unknown",
		1: "SystemError",
		2: "Disconnect",
		3: "AnotherLogin",
		4: "LoginTimeout",
	}
	DisconnectPush_Reason_value = map[string]int32{
		"Unknown":      0,
		"SystemError":  1,
		"Disconnect":   2,
		"AnotherLogin": 3,
		"LoginTimeout": 4,
	}
)

func (x DisconnectPush_Reason) Enum() *DisconnectPush_Reason {
	p := new(DisconnectPush_Reason)
	*p = x
	return p
}

func (x DisconnectPush_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DisconnectPush_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_c2s_login_proto_enumTypes[0].Descriptor()
}

func (DisconnectPush_Reason) Type() protoreflect.EnumType {
	return &file_c2s_login_proto_enumTypes[0]
}

func (x DisconnectPush_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DisconnectPush_Reason.Descriptor instead.
func (DisconnectPush_Reason) EnumDescriptor() ([]byte, []int) {
	return file_c2s_login_proto_rawDescGZIP(), []int{4, 0}
}

// 登陆请求.
type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // 令牌.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_c2s_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_c2s_login_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 登陆响应.
type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_c2s_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_c2s_login_proto_rawDescGZIP(), []int{1}
}

// 登陆游戏请求.
type LoginCharacterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`              // 用户ID
	AccountId     int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"` // 账号ID.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginCharacterReq) Reset() {
	*x = LoginCharacterReq{}
	mi := &file_c2s_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginCharacterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCharacterReq) ProtoMessage() {}

func (x *LoginCharacterReq) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginCharacterReq.ProtoReflect.Descriptor instead.
func (*LoginCharacterReq) Descriptor() ([]byte, []int) {
	return file_c2s_login_proto_rawDescGZIP(), []int{2}
}

func (x *LoginCharacterReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *LoginCharacterReq) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

// 登陆游戏响应.
type LoginCharacterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginCharacterResp) Reset() {
	*x = LoginCharacterResp{}
	mi := &file_c2s_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginCharacterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCharacterResp) ProtoMessage() {}

func (x *LoginCharacterResp) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginCharacterResp.ProtoReflect.Descriptor instead.
func (*LoginCharacterResp) Descriptor() ([]byte, []int) {
	return file_c2s_login_proto_rawDescGZIP(), []int{3}
}

// 断开连接推送.
type DisconnectPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        DisconnectPush_Reason  `protobuf:"varint,1,opt,name=reason,proto3,enum=c2s.DisconnectPush_Reason" json:"reason,omitempty"` // 原因.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectPush) Reset() {
	*x = DisconnectPush{}
	mi := &file_c2s_login_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectPush) ProtoMessage() {}

func (x *DisconnectPush) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_login_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectPush.ProtoReflect.Descriptor instead.
func (*DisconnectPush) Descriptor() ([]byte, []int) {
	return file_c2s_login_proto_rawDescGZIP(), []int{4}
}

func (x *DisconnectPush) GetReason() DisconnectPush_Reason {
	if x != nil {
		return x.Reason
	}
	return DisconnectPush_Unknown
}

// 心跳
type HeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	mi := &file_c2s_login_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_login_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_c2s_login_proto_rawDescGZIP(), []int{5}
}

type HeartbeatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResp) Reset() {
	*x = HeartbeatResp{}
	mi := &file_c2s_login_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResp) ProtoMessage() {}

func (x *HeartbeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_login_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResp.ProtoReflect.Descriptor instead.
func (*HeartbeatResp) Descriptor() ([]byte, []int) {
	return file_c2s_login_proto_rawDescGZIP(), []int{6}
}

var File_c2s_login_proto protoreflect.FileDescriptor

const file_c2s_login_proto_rawDesc = "" +
	"\n" +
	"\x0fc2s/login.proto\x12\x03c2s\" \n" +
	"\bLoginReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\v\n" +
	"\tLoginResp\"C\n" +
	"\x11LoginCharacterReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\"\x14\n" +
	"\x12LoginCharacterResp\"\xa0\x01\n" +
	"\x0eDisconnectPush\x122\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x1a.c2s.DisconnectPush.ReasonR\x06reason\"Z\n" +
	"\x06Reason\x12\v\n" +
	"\aUnknown\x10\x00\x12\x0f\n" +
	"\vSystemError\x10\x01\x12\x0e\n" +
	"\n" +
	"Disconnect\x10\x02\x12\x10\n" +
	"\fAnotherLogin\x10\x03\x12\x10\n" +
	"\fLoginTimeout\x10\x04\"\x0e\n" +
	"\fHeartbeatReq\"\x0f\n" +
	"\rHeartbeatRespB1Z/github.com/godyy/ggs/internal/core/proto/pb/c2sb\x06proto3"

var (
	file_c2s_login_proto_rawDescOnce sync.Once
	file_c2s_login_proto_rawDescData []byte
)

func file_c2s_login_proto_rawDescGZIP() []byte {
	file_c2s_login_proto_rawDescOnce.Do(func() {
		file_c2s_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_c2s_login_proto_rawDesc), len(file_c2s_login_proto_rawDesc)))
	})
	return file_c2s_login_proto_rawDescData
}

var file_c2s_login_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_c2s_login_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_c2s_login_proto_goTypes = []any{
	(DisconnectPush_Reason)(0), // 0: c2s.DisconnectPush.Reason
	(*LoginReq)(nil),           // 1: c2s.LoginReq
	(*LoginResp)(nil),          // 2: c2s.LoginResp
	(*LoginCharacterReq)(nil),  // 3: c2s.LoginCharacterReq
	(*LoginCharacterResp)(nil), // 4: c2s.LoginCharacterResp
	(*DisconnectPush)(nil),     // 5: c2s.DisconnectPush
	(*HeartbeatReq)(nil),       // 6: c2s.HeartbeatReq
	(*HeartbeatResp)(nil),      // 7: c2s.HeartbeatResp
}
var file_c2s_login_proto_depIdxs = []int32{
	0, // 0: c2s.DisconnectPush.reason:type_name -> c2s.DisconnectPush.Reason
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_c2s_login_proto_init() }
func file_c2s_login_proto_init() {
	if File_c2s_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_c2s_login_proto_rawDesc), len(file_c2s_login_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_c2s_login_proto_goTypes,
		DependencyIndexes: file_c2s_login_proto_depIdxs,
		EnumInfos:         file_c2s_login_proto_enumTypes,
		MessageInfos:      file_c2s_login_proto_msgTypes,
	}.Build()
	File_c2s_login_proto = out.File
	file_c2s_login_proto_goTypes = nil
	file_c2s_login_proto_depIdxs = nil
}
