// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: c2s/pid.proto

package c2s

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PID 协议ID.
// 如果协议消息结构来common, 可在其注释中添加 /from_common 标识.
type PID int32

const (
	PID_PUnknown            PID = 0
	PID_PError              PID = 1  // 通用错误. /from_common.
	PID_PLoginReq           PID = 2  // 网关登陆请求.
	PID_PLoginResp          PID = 3  // 网关登陆响应.
	PID_PLoginCharacterReq  PID = 4  // 游戏角色登陆请求.
	PID_PLoginCharacterResp PID = 5  // 游戏角色登陆响应.
	PID_PDisconnectPush     PID = 6  // 断开连接推送.
	PID_PHeartbeatReq       PID = 7  // 心跳请求.
	PID_PHeartbeatResp      PID = 8  // 心跳响应.
	PID_PModifyNameReq      PID = 9  // 修改名称请求.
	PID_PModifyNameResp     PID = 10 // 修改名称响应.
)

// Enum value maps for PID.
var (
	PID_name = map[int32]string{
		0:  "PUnknown",
		1:  "PError",
		2:  "PLoginReq",
		3:  "PLoginResp",
		4:  "PLoginCharacterReq",
		5:  "PLoginCharacterResp",
		6:  "PDisconnectPush",
		7:  "PHeartbeatReq",
		8:  "PHeartbeatResp",
		9:  "PModifyNameReq",
		10: "PModifyNameResp",
	}
	PID_value = map[string]int32{
		"PUnknown":            0,
		"PError":              1,
		"PLoginReq":           2,
		"PLoginResp":          3,
		"PLoginCharacterReq":  4,
		"PLoginCharacterResp": 5,
		"PDisconnectPush":     6,
		"PHeartbeatReq":       7,
		"PHeartbeatResp":      8,
		"PModifyNameReq":      9,
		"PModifyNameResp":     10,
	}
)

func (x PID) Enum() *PID {
	p := new(PID)
	*p = x
	return p
}

func (x PID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PID) Descriptor() protoreflect.EnumDescriptor {
	return file_c2s_pid_proto_enumTypes[0].Descriptor()
}

func (PID) Type() protoreflect.EnumType {
	return &file_c2s_pid_proto_enumTypes[0]
}

func (x PID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PID.Descriptor instead.
func (PID) EnumDescriptor() ([]byte, []int) {
	return file_c2s_pid_proto_rawDescGZIP(), []int{0}
}

var File_c2s_pid_proto protoreflect.FileDescriptor

const file_c2s_pid_proto_rawDesc = "" +
	"\n" +
	"\rc2s/pid.proto\x12\x03c2s*\xd4\x01\n" +
	"\x03PID\x12\f\n" +
	"\bPUnknown\x10\x00\x12\n" +
	"\n" +
	"\x06PError\x10\x01\x12\r\n" +
	"\tPLoginReq\x10\x02\x12\x0e\n" +
	"\n" +
	"PLoginResp\x10\x03\x12\x16\n" +
	"\x12PLoginCharacterReq\x10\x04\x12\x17\n" +
	"\x13PLoginCharacterResp\x10\x05\x12\x13\n" +
	"\x0fPDisconnectPush\x10\x06\x12\x11\n" +
	"\rPHeartbeatReq\x10\a\x12\x12\n" +
	"\x0ePHeartbeatResp\x10\b\x12\x12\n" +
	"\x0ePModifyNameReq\x10\t\x12\x13\n" +
	"\x0fPModifyNameResp\x10\n" +
	"B1Z/github.com/godyy/ggs/internal/core/proto/pb/c2sb\x06proto3"

var (
	file_c2s_pid_proto_rawDescOnce sync.Once
	file_c2s_pid_proto_rawDescData []byte
)

func file_c2s_pid_proto_rawDescGZIP() []byte {
	file_c2s_pid_proto_rawDescOnce.Do(func() {
		file_c2s_pid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_c2s_pid_proto_rawDesc), len(file_c2s_pid_proto_rawDesc)))
	})
	return file_c2s_pid_proto_rawDescData
}

var file_c2s_pid_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_c2s_pid_proto_goTypes = []any{
	(PID)(0), // 0: c2s.PID
}
var file_c2s_pid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_c2s_pid_proto_init() }
func file_c2s_pid_proto_init() {
	if File_c2s_pid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_c2s_pid_proto_rawDesc), len(file_c2s_pid_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_c2s_pid_proto_goTypes,
		DependencyIndexes: file_c2s_pid_proto_depIdxs,
		EnumInfos:         file_c2s_pid_proto_enumTypes,
	}.Build()
	File_c2s_pid_proto = out.File
	file_c2s_pid_proto_goTypes = nil
	file_c2s_pid_proto_depIdxs = nil
}
