// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: c2s/player.proto

package c2s

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 修改名称请求.
type ModifyNameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 新名称.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyNameReq) Reset() {
	*x = ModifyNameReq{}
	mi := &file_c2s_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyNameReq) ProtoMessage() {}

func (x *ModifyNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyNameReq.ProtoReflect.Descriptor instead.
func (*ModifyNameReq) Descriptor() ([]byte, []int) {
	return file_c2s_player_proto_rawDescGZIP(), []int{0}
}

func (x *ModifyNameReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 修改名称响应
type ModifyNameResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 新名称.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyNameResp) Reset() {
	*x = ModifyNameResp{}
	mi := &file_c2s_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyNameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyNameResp) ProtoMessage() {}

func (x *ModifyNameResp) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyNameResp.ProtoReflect.Descriptor instead.
func (*ModifyNameResp) Descriptor() ([]byte, []int) {
	return file_c2s_player_proto_rawDescGZIP(), []int{1}
}

func (x *ModifyNameResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_c2s_player_proto protoreflect.FileDescriptor

const file_c2s_player_proto_rawDesc = "" +
	"\n" +
	"\x10c2s/player.proto\x12\x03c2s\"#\n" +
	"\rModifyNameReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"$\n" +
	"\x0eModifyNameResp\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04nameB1Z/github.com/godyy/ggs/internal/core/proto/pb/c2sb\x06proto3"

var (
	file_c2s_player_proto_rawDescOnce sync.Once
	file_c2s_player_proto_rawDescData []byte
)

func file_c2s_player_proto_rawDescGZIP() []byte {
	file_c2s_player_proto_rawDescOnce.Do(func() {
		file_c2s_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_c2s_player_proto_rawDesc), len(file_c2s_player_proto_rawDesc)))
	})
	return file_c2s_player_proto_rawDescData
}

var file_c2s_player_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_c2s_player_proto_goTypes = []any{
	(*ModifyNameReq)(nil),  // 0: c2s.ModifyNameReq
	(*ModifyNameResp)(nil), // 1: c2s.ModifyNameResp
}
var file_c2s_player_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_c2s_player_proto_init() }
func file_c2s_player_proto_init() {
	if File_c2s_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_c2s_player_proto_rawDesc), len(file_c2s_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_c2s_player_proto_goTypes,
		DependencyIndexes: file_c2s_player_proto_depIdxs,
		MessageInfos:      file_c2s_player_proto_msgTypes,
	}.Build()
	File_c2s_player_proto = out.File
	file_c2s_player_proto_goTypes = nil
	file_c2s_player_proto_depIdxs = nil
}
